name: quizflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

  path: any
  flip_card: ^0.7.0
  share_plus: ^9.0.0
  file_selector: ^1.0.3
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpeg"
  
flutter:
  uses-material-design: true
